### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by alfredonodo** [calleluks/Tofu#123]
Hi,
I am moving away from Authenticator because it seems to have been abandoned. Firstly, I would like to know if Tofu is still supported and developed and secondly, I would like to know if it supports all the features I need (encrypted storage, backup support (local, icloud and openPGP)).
Thank you very much

**Comment by calleluks** [comment]
Hey @alfredonodo, I haven't had much time to work in the app for quite a while. Tofu stores secrets in the iOS keychain which is responsible for encryption. These keychain items will be part of password protected iOS backups performed with iTunes or Finder on a Mac. Unfortunately, the don't seem to be part of iCloud backups. There's no support for PGP.
