### ISSUE TITLE
Add an icon for twitch.tv

### ISSUE THREAD

**Issue by R4z0r112** [calleluks/Tofu#64]
Hi! Could you please add an icon for Example?

Their website is at https://www.twitch.tv/.

Icon could be like this:
![twitch](https://user-images.githubusercontent.com/80312122/110436396-788e6a80-80b4-11eb-8ff2-43dca0f99907.png)

Thanks a lot for this great app!

**Comment by calleluks** [comment]
Hey @R4z0r112, I'm glad you like the app!

I'd be happy to add the icon. Does it says "Twitch" or "twitch.tv" next to the account in Tofu?
