### ISSUE TITLE
iOS 12.5.x support

### ISSUE THREAD

**Issue by drvink** [calleluks/Tofu#73]
I have an iPhone 5S, so I can't run iOS 13. It appears that previous versions of Tofu worked on iOS 12--would you mind supporting it again? (I don't have a Mac, otherwise I'd try to fix this myself and send a PR--sorry for making a shameless feature request!)

**Comment by eutampieri** [comment]
Download it on a newer device (if you have one) and download it again from the purchased section so you get the last compatible version

**Comment by drvink** [comment]
One weird trick for never buying a new phone discovered by a local Github--Apple HATES him!! (Your suggestion worked: I "purchased" it using iTunes on Windows, then grabbed it via the store on my phone.)

Thanks @eutampieri!
