### ISSUE TITLE
Icon request: Sony

### ISSUE THREAD

**Issue by Araraura** [calleluks/Tofu#81]
Hey there, could you please add an icon for Sony (For Playstation and such)?
Their accounts can use 2FA but there's no icon for them.
Here's the icon:
![favicon](https://user-images.githubusercontent.com/25017422/120446302-f216bb80-c378-11eb-9665-77d125475bad.png)

Their website is at https://sony.com.

**Comment by RazziaDK** [comment]
I have added a Sony in the following pull request, although it is just a small Sony icon. 
https://github.com/calleluks/Tofu/pull/84
