### ISSUE TITLE
An image (icon) from NexusMods doesn't shown in application (iPhone)

### ISSUE THREAD

**Issue by OGDB89** [calleluks/Tofu#91]
Hello, is there any method how to fix that? I love app but some icons (NexusMods, CTemplar) doesn't show in application.

Thank you for this super great program, Calleluks!

**Comment by RazziaDK** [comment]
Have you updated to the latest version of the app? (Released yesterday)
If yes, would you please write what issuer you see in the app?
To see it, click edit, select the account in question. Then you will see the issuer in the second line.

**Comment by OGDB89** [comment]
> 
> 
> Have you updated to the latest version of the app? (Released yesterday) If yes, would you please write what issuer you see in the app? To see it, click edit, select the account in question. Then you will see the issuer in the second line.

Hi RazziaDK, i did update now (I haven't seen it) but i don't see NexusMods icon.
Issuer in the app: **NexusMods**
I don't know why i don't see this icon. Amazon icon works, PayPal too. 

I am wondering is it a possible to add CTemplar icon i was trying to add by myself by since my knowledge is below 0 i can't figure how to run command from root. 

Kind regards

**Comment by OGDB89** [comment]
**RazziaDK** i did solve the problem by myself.

What i did:

1. I have opened this link https://github.com/calleluks/Tofu/blob/master/Tofu/AccountCell.swift#L15

2. Line 85: Nexus Mods (In my app on iPhone NexusMods was without space)

3. I've put space in my app in iPhone in issuer field. Wrote: **Nexus Mods**. And i saw an image! Perfect! Thank you very much for helping!

P.s. please add CTemplar icon.

**Comment by RazziaDK** [comment]
Great to hear. I just created a Nexus Mods account to see if there is a space or not, if a new users creates 2FA on a Nexus Mods account today. My issuer field was "Nexus Mods", so I think the app has it right at the moment. :-)

**Comment by RazziaDK** [comment]
> 
> P.s. please add CTemplar icon.

I added CTemplar in this pull request: https://github.com/calleluks/Tofu/pull/92
So I will most likely be in the next version of the app.
